/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Payment = IDL.Record({
  'month' : IDL.Nat,
  'paid' : IDL.Bool,
  'year' : IDL.Nat,
  'childId' : IDL.Nat,
  'paidDate' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Child = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'joiningDate' : Time,
  'mobile' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChild' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteChild' : IDL.Func([IDL.Nat], [], []),
  'getAllPayments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(Payment)))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChild' : IDL.Func([IDL.Nat], [IDL.Opt(Child)], ['query']),
  'getChildren' : IDL.Func([], [IDL.Vec(Child)], ['query']),
  'getPayments' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
  'getPaymentsDue' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPayment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateChild' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Payment = IDL.Record({
    'month' : IDL.Nat,
    'paid' : IDL.Bool,
    'year' : IDL.Nat,
    'childId' : IDL.Nat,
    'paidDate' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Child = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'joiningDate' : Time,
    'mobile' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChild' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteChild' : IDL.Func([IDL.Nat], [], []),
    'getAllPayments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(Payment)))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChild' : IDL.Func([IDL.Nat], [IDL.Opt(Child)], ['query']),
    'getChildren' : IDL.Func([], [IDL.Vec(Child)], ['query']),
    'getPayments' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
    'getPaymentsDue' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPayment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateChild' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };